FROM laradock/php-fpm:7.0--1.2

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

ADD ./test.ini /usr/local/etc/php/conf.d
ADD ./test.pool.conf /usr/local/etc/php-fpm.d/

RUN rm -r /var/lib/apt/lists/*

RUN usermod -u 1000 www-data

WORKDIR /var/www/test

CMD ["php-fpm"]

EXPOSE 9000
